#!url=https://raw.githubusercontent.com/dhungx/modules-shadowrocket/refs/heads/main/locket.module
#!name=Locket-Gold  ViBoss Studio
#!desc=Locket unlock Gold
# Update: 07/09/2024
# Telegram: https://t.me/Dhungx

[Script]
# By ViBoss Studio
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/dhungx/modules-shadowrocket/refs/heads/main/js/locket/Locket.js, requires-body=true, max-size=-1, timeout=60

deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/dhungx/modules-shadowrocket/refs/heads/main/js/locket/deleteHeader.js, timeout=60

[MITM]
hostname = %APPEND% api.revenuecat.com