#!url=https://raw.githubusercontent.com/dhungx/modules-shadowrocket/refs/heads/main/locket.module
#!name=Locket Gold 
#!desc=Unlock Gold 
# Telegram: https://t.me/dhungx
# Instagaram: https://www.instagram.com/only.dohungx_/

[Script]
# ~ By Dohungx
# ～ Egern transfer to Shadowrocket & Surge & LanceX
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/dhungx/modules-shadowrocket/refs/heads/main/js/locket/Locket.js, requires-body=true, max-size=-1, timeout=60

deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/dhungx/modules-shadowrocket/refs/heads/main/js/locket/deleteHeader.js, timeout=60

[MITM]
hostname = %APPEND% api.revenuecat.com